### ISSUE TITLE
ERROR: Dialect undefined does not support db:create / db:drop commands

### ISSUE THREAD

**Issue by d4hines** [taylonr/postman#2]
I'm hoping I'm just doing a dumb-dumb, but I can't seem to create the db with sequelize-cli.

```
C:\repos\postman>npm run db:create

> postman@0.0.0 db:create C:\repos\postman
> sequelize db:create && npm run db:migrate && npm run db:seed


Sequelize CLI [Node: 8.9.4, CLI: 3.2.0, ORM: 4.28.0]

WARNING: This version of Sequelize CLI is not fully compatible with Sequelize v4. https://github.com/sequelize/cli#sequelize-support

Loaded configuration file "server\config\config.json".

ERROR: Dialect undefined does not support db:create / db:drop commands

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! postman@0.0.0 db:create: `sequelize db:create && npm run db:migrate && npm run db:seed`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the postman@0.0.0 db:create script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dhines\AppData\Roaming\npm-cache\_logs\2018-04-26T16_11_26_029Z-debug.log
```

Thoughts?

**Comment by taylonr** [comment]
Make sure the dialect property in config.json is

"postgres"

and that it didn't get changed to something else (e.g. postgresql).

Here's an example config file:
```
{
  "development": {
    "username": "postgres",
    "password": "secret1",
    "database": "postman_dev",
    "host": "localhost",
    "port": 5432,
    "dialect": "postgres"
  },
  "test": {
    "username": "postgres",
    "password": "secret1",
    "database": "postman_test",
    "host": "localhost",
    "port": 5432,
    "dialect": "postgres"
  }
}
```

**Comment by d4hines** [comment]
That's exactly what I have in my config file. It almost seems like it would be an issue with the sequelizer-cli version or something, but I'm using your lock-file. What version of Postrgres are you using?

**Comment by taylonr** [comment]
I believe I was using version 10.

I wonder if there's a problem loading the config file, because it's saying the dialect is "undefined"

**Comment by d4hines** [comment]
Yeah, it's got to be something like that. It's a bit of a long shot but what about Node version? I'm on Node v8.9.4 and and npm v5.6.0.

**Comment by taylonr** [comment]
I think I was on node 9 when I created the course, I know I've since upgraded to 9.8 and haven't had problems.

I'd tell you to just create the DB that config file is used for all the queries so you wouldn't be able to do anything with the DB.

Which command did you run that produced this error?

**Comment by d4hines** [comment]
I won't have access this weekend; however, the the only changes I made to
your repo we're updating the password in the config. It's exactly the same
otherwise. If I understand how lock files work, I should have had the exact
versions of every package you used, right? That means it has to be my
environment (Node, Windows, something...), correct?

**Comment by taylonr** [comment]
Yeah, it must be something on your environment. I just pulled latest, and spun up a psql DB, set my password to "secret" and tried it, and the database was created without issue.

I know that people have done the course on Windows, so I'm kind of at a loss for why it's not working for youl

**Comment by d4hines** [comment]
I'm getting what I need from the course without following along in your
repo (all the pieces are mapping 1:1 to my current project, so it's working
out just fine). It hurts my pride to let a bug win, but I'm happy to chalk
this one up to a loss (heck, it could be some crazy settings on the
corporate network, since this is at work) and just close this issue until
someone else runs into the same.

**Comment by marvtdawson** [comment]
Hi Taylor,  I am new to pluralsight and the course, I am running into a issue with the config/config.json when I run the npm run db:create command.   The error is "Error: Cannot find module '/my_path/postman_projectName/config/config.json'"  I am running Node 9.10.1 and npm 6.4.0  using Visual Code.   Any suggestions or thoughts on this issue?  

Thanks in advance

**Comment by taylonr** [comment]
What is the path that you're running `npm run db:create` from?

**Comment by taylonr** [comment]
I'm not sure. 

From your bash shell, you can cd into my_path/postman_projectName/config/ and is there a config.json file in there?

**Comment by joshuaneedham** [comment]
I was running into this issue and removed the username from the config file altogether and it worked.

**Comment by dwatow** [comment]
try it
```shell
$ sequelize db:create --env=test
```

**Comment by taylonr** [comment]
This project no longer uses a postgres database. It now uses JSON API which
has an in memory database. So there is no longer a need to run db:create

**Comment by MrSharpp** [comment]
> try it
> 
> ```shell
> $ npm run db:create --env=test
> ```

Thanks, the issue was fixed. But every time I have to add --env=development, how can I make that sequelize-cli get this environment variable from a persistent source?

**Comment by taylonr** [comment]
I'm going to refer to the comment before yours almost 2 years ago. This project no longer uses postgres, and therefore no longer uses a postgres database.

**Comment by Johnsonakanmu** [comment]
I encountered difficulties creating a database with Sequelize CLI. To address the issue, I attempted running the following command:
npx sequelize-cli db:create --env=test

However, the problem persisted. Eventually, I found a solution that worked for me:

npx sequelize-cli db:create --env=development
